import type { ScanResult } from '../types/analysis.js';
import type { AIAgentPrompt, RefactorPlan } from '../types/plan.js';
import type { SkillMatch } from '../types/skill.js';

const DEFAULT_BUDGET = 4000;

export interface BuildPromptOptions {
  budget?: number;
}

export function buildAIAgentPrompt(plan: RefactorPlan, scan: ScanResult, primarySkill: SkillMatch | null, options: BuildPromptOptions = {}): AIAgentPrompt {
  const constraints = [
    'Preserve existing behavior unless a step explicitly says otherwise.',
    'Preserve and update tests with each refactor.',
    'Update imports after moving or extracting code.',
    'Avoid introducing new circular dependencies.',
    'Do not delete source code until replacement behavior is covered.'
  ];
  const projectContext = [
    `Target: ${scan.summary.targetDir}`,
    `Files analyzed: ${scan.summary.totalFiles}`,
    `Health: ${plan.source.healthLabel}`,
    `Complexity: ${plan.estimatedComplexity}`,
    `Risk: ${plan.estimatedRisk}`,
    `Top issues: ${(scan.issues ?? []).slice(0, 5).map((issue) => `${issue.severity} ${issue.category}: ${issue.message}`).join('; ') || 'none'}`
  ].join('\n');
  const skillBlueprint = primarySkill ? renderSkillBlueprint(primarySkill) : 'No confident primary architecture skill was detected. Use the generic plan and do not invent stack-specific rules.';
  const renderedPlan = plan.phases
    .map((phase) => [
      `## ${phase.name}`,
      phase.description,
      ...phase.steps.map((step) => `${step.stepNumber}. ${step.what} Target: ${step.targetFile}. Dependencies: ${step.dependencyNotes}`)
    ].join('\n'))
    .join('\n\n');
  const prompt: AIAgentPrompt = {
    projectContext,
    skillBlueprint,
    plan: renderedPlan,
    constraints,
    budgetStatus: 'within_budget'
  };

  return trimPrompt(prompt, options.budget ?? DEFAULT_BUDGET);
}

function renderSkillBlueprint(match: SkillMatch): string {
  const { skill } = match;
  const required = skill.structure.requiredDirs.map((entry) => `- ${entry.path}: ${entry.purpose}`).join('\n') || '- none';
  const recommended = skill.structure.recommendedDirs.map((entry) => `- ${entry.path}: ${entry.purpose}`).join('\n') || '- none';
  const separation = skill.separation.rules.map((rule) => `- ${rule.concern} belongs in ${rule.belongsIn}`).join('\n') || '- none';
  const naming = Object.entries(skill.patterns.naming ?? {}).map(([key, value]) => `- ${key}: ${value}`).join('\n') || '- none';
  const dataFlow = skill.patterns.dataFlow ? [`Direction: ${skill.patterns.dataFlow.direction}`, ...skill.patterns.dataFlow.rules.map((rule) => `- ${rule}`)].join('\n') : 'none';
  const antiPatterns = skill.antiPatterns.map((item) => `- ${item.severity}: ${item.description}`).join('\n') || '- none';

  return [
    `Matched skill: ${skill.name} (${skill.id}) at ${match.confidence} confidence`,
    'Target structure:',
    required,
    'Recommended structure:',
    recommended,
    'Separation rules:',
    separation,
    'Naming conventions:',
    naming,
    'Pattern expectations:',
    dataFlow,
    'Anti-patterns:',
    antiPatterns
  ].join('\n');
}

function trimPrompt(prompt: AIAgentPrompt, budget: number): AIAgentPrompt {
  const serialized = serializePrompt(prompt);
  if (estimateTokens(serialized) <= budget) return prompt;

  const trimmedPlan = prompt.plan.split('\n').slice(0, 80).join('\n');
  return {
    ...prompt,
    plan: `${trimmedPlan}\n\n[Trimmed to fit prompt budget; keep highest-priority steps above.]`,
    budgetStatus: 'trimmed'
  };
}

export function serializePrompt(prompt: AIAgentPrompt): string {
  return [
    'You are implementing a refactoring plan generated by architect.',
    '',
    'PROJECT CONTEXT',
    prompt.projectContext,
    '',
    'ARCHITECTURE BLUEPRINT',
    prompt.skillBlueprint,
    '',
    'ORDERED PLAN',
    prompt.plan,
    '',
    'SAFETY CONSTRAINTS',
    ...prompt.constraints.map((constraint) => `- ${constraint}`),
    '',
    `Budget status: ${prompt.budgetStatus}`
  ].join('\n');
}

export function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}
